INSERT INTO FOOD(NAME, KCAL, FOOD_TYPE)
VALUES('Ćevapčići', 1000, 'MEAT');

INSERT INTO FOOD(NAME, KCAL, FOOD_TYPE)
VALUES('Pileći file na žaru', 500, 'MEAT');

INSERT INTO FOOD(NAME, KCAL, FOOD_TYPE)
VALUES('Steak slabo pečen jako krvav', 2000, 'MEAT');